#!/usr/bin/env bash
# install-openclaw.sh — Idempotent OpenClaw setup for Ubuntu 24.04
# Run as root (or with sudo). Targets Hetzner/Linode/OVH — any provider.
# Vultr-specific bits are stripped; you supply your own model provider.
#
# ════════════════════════════════════════════════════════════════════════
# SOURCE: Generated by OpenClaw 2026.4.5 on the Vultr Marketplace box at
# 209.250.226.99, captured 2026-04-21 before the box was destroyed.
#
# ⚠️  THIS IS THE RAW OUTPUT — NOT YET TESTED ON HETZNER. See REVIEW.md
#     in this folder for the known bugs we need to fix before running it
#     in production. Captured as-is for traceability.
# ════════════════════════════════════════════════════════════════════════

set -euo pipefail

# ── Configuration (edit these) ──────────────────────────────────────────
DOMAIN="${DOMAIN:?Set DOMAIN to your fully-qualified domain}"
OPENAI_API_KEY="${OPENAI_API_KEY:?Set OPENAI_API_KEY}"
GATEWAY_TOKEN="${GATEWAY_TOKEN:?Set GATEWAY_TOKEN}"          # generate: openssl rand -hex 16
CODE_PASSWORD="${CODE_PASSWORD:-}"                           # optional: code-server password
ADMIN_USER="${SUDO_USER:-openclaw}"                          # unprivileged service user
OPENCLAW_VER="2026.4.5"
CLAWHUB_VER="0.9.0"
NODE_MAJOR="22"

# ── 1. System packages ─────────────────────────────────────────────────
apt-get update -qq
apt-get install -y -qq curl wget git uidmap \
  ca-certificates gnupg lsb-release

# ── 2. Node.js (Nodesource 22.x) ──────────────────────────────────────
if ! command -v node &>/dev/null || [[ "$(node -v)" != v${NODE_MAJOR}.* ]]; then
  curl -fsSL https://deb.nodesource.com/setup_${NODE_MAJOR}.x | bash -
  apt-get install -y -qq nodejs
fi

# ── 3. Caddy (official repo) ───────────────────────────────────────────
if ! command -v caddy &>/dev/null; then
  apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https
  curl -1sLf "https://dl.cloudsmith.io/public/caddy/stable/gpg.key" \
    | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf "https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt" \
    | tee /etc/apt/sources.list.d/caddy-stable.list
  apt-get update -qq
  apt-get install -y -qq caddy
fi

# ── 4. Docker (official repo) ──────────────────────────────────────────
if ! command -v docker &>/dev/null; then
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
    | tee /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io \
    docker-buildx-plugin docker-compose-plugin docker-ce-rootless-extras
  systemctl enable --now docker
fi

# ── 5. code-server (optional) ──────────────────────────────────────────
if [[ -n "${CODE_PASSWORD}" ]] && ! command -v code-server &>/dev/null; then
  curl -fsSL https://code-server.dev/install.sh | bash
fi

# ── 6. OpenClaw + clawhub ─────────────────────────────────────────────
npm install -g "openclaw@${OPENCLAW_VER}" "clawhub@${CLAWHUB_VER}"

# ── 7. Service user ────────────────────────────────────────────────────
id "$ADMIN_USER" &>/dev/null || useradd -m -s /bin/bash "$ADMIN_USER"

# ── 8. systemd user unit ───────────────────────────────────────────────
loginctl enable-linger "$ADMIN_USER" 2>/dev/null || true
mkdir -p "/home/$ADMIN_USER/.config/systemd/user"

cat > "/home/$ADMIN_USER/.config/systemd/user/openclaw-gateway.service" <<'UNIT'
[Unit]
Description=OpenClaw Gateway
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=/usr/bin/node /usr/lib/node_modules/openclaw/dist/index.js gateway --port 18789
Restart=always
RestartSec=5
TimeoutStopSec=30
TimeoutStartSec=30
SuccessExitStatus=0 143
KillMode=control-group
Environment=HOME=/home/openclaw
Environment=TMPDIR=/tmp
Environment=PATH=/usr/bin:/home/openclaw/.local/bin:/home/openclaw/.npm-global/bin:/home/openclaw/bin:/home/openclaw/.volta/bin:/home/openclaw/.asdf/shims:/home/openclaw/.bun/bin:/home/openclaw/.nvm/current/bin:/home/openclaw/.fnm/current/bin:/home/openclaw/.local/share/pnpm:/usr/local/bin:/bin
Environment=OPENCLAW_GATEWAY_PORT=18789
Environment=OPENCLAW_SYSTEMD_UNIT=openclaw-gateway.service
Environment=OPENCLAW_SERVICE_MARKER=openclaw
Environment=OPENCLAW_SERVICE_KIND=gateway

[Install]
WantedBy=default.target
UNIT

chown -R "$ADMIN_USER:$ADMIN_USER" "/home/$ADMIN_USER/.config"

# ── 9. openclaw.json (sanitised template) ──────────────────────────────
mkdir -p "/home/$ADMIN_USER/.openclaw"
cat > "/home/$ADMIN_USER/.openclaw/openclaw.json" <<CFG
{
  "models": {
    "providers": {
      "my-provider": {
        "baseUrl": "\${MODEL_BASE_URL:-https://api.openai.com/v1}",
        "apiKey": "\${OPENAI_API_KEY}",
        "auth": "bearer",
        "api": "openai-completions",
        "models": [
          {
            "id": "gpt-4o",
            "name": "GPT-4o",
            "api": "openai-completions",
            "input": ["text", "image"],
            "contextWindow": 128000,
            "maxTokens": 16384
          }
        ]
      }
    }
  },
  "agents": {
    "defaults": {
      "compaction": {
        "mode": "default",
        "identifierPolicy": "strict"
      },
      "timeoutSeconds": 86400
    }
  },
  "commands": {
    "native": "auto",
    "nativeSkills": "auto",
    "restart": true,
    "ownerDisplay": "raw"
  },
  "gateway": {
    "port": 18789,
    "mode": "local",
    "bind": "lan",
    "controlUi": {
      "allowedOrigins": [
        "http://127.0.0.1:18789",
        "http://127.0.0.1",
        "https://\${DOMAIN}"
      ]
    },
    "auth": {
      "mode": "token",
      "token": "\${GATEWAY_TOKEN}"
    },
    "trustedProxies": ["127.0.0.1"]
  }
}
CFG
chown -R "$ADMIN_USER:$ADMIN_USER" "/home/$ADMIN_USER/.openclaw"

# ── 10. Caddy reverse-proxy ────────────────────────────────────────────
# NOTE: The Vultr setup used ZeroSSL EAB + a *.vultropenclaw.com wildcard.
# On generic hosts, just use Caddy's default Let's Encrypt via HTTP-01.
# Ensure DNS A record for ${DOMAIN} → this machine's public IP.

cat > /etc/caddy/Caddyfile <<CADDY
\${DOMAIN} {
    # Caddy auto-provisions Let's Encrypt certs via HTTP-01 challenge.
    # If you need DNS-01 (wildcards), add: issuer acme { ... }
    tls

    basic_auth {
        clawmine \$(caddy hash-password --plaintext 'CHANGE_ME')
    }

    handle /code/* {
        uri strip_prefix /code
        reverse_proxy 127.0.0.1:6969
    }

    handle {
        reverse_proxy 127.0.0.1:18789 {
            header_up -X-Real-IP
            header_up -X-Forwarded-For
            transport http {
                versions 1.1
            }
        }
    }
}
CADDY
systemctl restart caddy

# ── 11. Start gateway ──────────────────────────────────────────────────
sudo -u "$ADMIN_USER" XDG_RUNTIME_DIR="/run/user/$(id -u "$ADMIN_USER")" \
  systemctl --user daemon-reload
sudo -u "$ADMIN_USER" XDG_RUNTIME_DIR="/run/user/$(id -u "$ADMIN_USER")" \
  systemctl --user enable --now openclaw-gateway.service

# ── 12. Workspace bootstrap ────────────────────────────────────────────
mkdir -p "/home/$ADMIN_USER/.openclaw/workspace"
chown -R "$ADMIN_USER:$ADMIN_USER" "/home/$ADMIN_USER/.openclaw/workspace"

# ── Verification ───────────────────────────────────────────────────────
echo "=== Verification ==="
sleep 3

# Gateway on :18789
if curl -sf http://127.0.0.1:18789/health >/dev/null 2>&1; then
  echo "✅ Gateway listening on :18789"
else
  echo "❌ Gateway NOT responding on :18789 — check: sudo -u $ADMIN_USER journalctl --user -u openclaw-gateway"
fi

# Caddy on :443
if curl -sf https://"${DOMAIN}"/ >/dev/null 2>&1; then
  echo "✅ Caddy serving HTTPS on :443"
else
  echo "⚠️  Caddy HTTPS not yet ready (DNS propagation or cert issuance may take a minute)"
fi

echo "=== Done ==="
